name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Initialize app
        run: make setup

      - name: Run Rubocop
        run: make lint

      - name: Run Tests
        run: make test
